### ISSUE TITLE
Kernel died

### ISSUE THREAD

**Issue by LauAvinyo** [harmslab/notebooks-nonlinear-high-order-epistasis#1]
Hello, 
I am trying to replicate the figures using the jupyter notebooks, but each time I want to use model.fit() or power.fit() the kernel dies. Do you know which could be the problem?
By the way, congratulations for your article.

Best regards, 
Laura

**Comment by Zsailer** [comment]
Hi @LauAvinyo,

Are you running the notebooks on the Binder web service? Or locally on your computer? If you're running them locally, are you using a Mac, Windows, or Linux machine? 

The fitting methods use a Cython extension under the hood. It's possible that this extension may have failed to compile correctly, or it may be running out of memory (although the datasets in these notebooks are relatively small). My suspicion is that something went wrong with that extension. If you wouldn't mind telling me your OS, I'll do some digging.

**Comment by LauAvinyo** [comment]
Hi, 
I am running on my local computer and I am using Linux.

**Comment by Zsailer** [comment]
That's odd. How did you install the `epistasis` package?

**Comment by LauAvinyo** [comment]
Hi,
I have fixed the problem. (I just needed to upload one package on Anaconda).

**Comment by Zsailer** [comment]
Great! Glad it works! 

Closing.
